### ISSUE TITLE
After win, allow to hover over every word dot to reveal the unguessed words nearby?

### ISSUE THREAD

**Issue by rrauenza** [jsettlem/pimantle#11]
Is that even possible, or are there too many words?   Maybe restrict it to a radius from the center?

**Comment by jsettlem** [comment]
That's what the "explore" button should do after you win.

**Comment by rrauenza** [comment]
Ah!  I just saw this in your video as well

https://www.youtube.com/shorts/ai-eoItlmoI

So was just now trying to figure out how I'm missing that!
